### ISSUE TITLE
Add Encore Musicians badge

### ISSUE THREAD

**Issue by tom-ai** [tom-ai/sophia-website#33]
Add the following embed code to the footer. Somewhere that looks nice. 

```

<!--Encore Button Generated 12th January 2024 at 5:55pm; Copyright Encore 2024--><a href='https://encoremusicians.com/hire/violists?utm_source=badge&utm_medium=web&utm_campaign=verified_badge&utm_content=dark-small' target="_parent"><img src='https://encoremusicians.com/img/embeds/badge-dark.svg' alt='Book Sophia Dignam on Encore Musicians' style='width: 80px; height: 80px;'/></a>

```

Encore Musicians is an online bookings agent, of which Sophia is registered with. This button will boost SEO rankings.

**Comment by tom-ai** [comment]
It's not super easy to add embeds as components. May be easier just to add it to the HTML/root layout. 

Otherwise it's the `dangerously set inner html`

**Comment by iampaandey** [comment]
please assign this to me

**Comment by tom-ai** [comment]
@iampaandey Hi Raghav let me see if I can set this up for you. I'm currently away from laptop until March

**Comment by iampaandey** [comment]
okay ! I will do it and raise a PR tomorrow.
