### ISSUE TITLE
Footer has a lot of unnecessary spacing between the text on mobile devices

### ISSUE THREAD

**Issue by hannahro15** [tom-ai/sophia-website#40]
I discovered this looking at the website on my mobile just now with there being a lot of spacing between the footer text near the bottom of the website.

There is also a rectangular bar I can see almost the same colour as the background, a darkish colour. I'm not sure if it is part of the footer or not.

**Comment by tom-ai** [comment]
Thanks Hannah I've removed the grey block and reduced space at the top of the footer.
